export enum DependencyCategoryEnum {
    EXERCISE_DESCRIPTION,
    FORMULA,
    POLYGON_TYPE,
    OF_POINTS_PAIRS,
    OF_LINES,
    OF_CIRCLES,
    OF_ANGLES,
    OF_LINE_AND_ANGLE,
    OF_LINE_AND_CIRCLE,
    OF_LINE_AND_POINTS_PAIR,
    OF_CIRCLE_AND_POLYGON,
    OF_POINTS_PAIRS_PAIR_AND_POINTS_PAIR,
    OF_POLYGONS,
    OF_POLYGON_AND_POINTS_PAIRS,
    OF_POLYGON_AND_EXPRESSION
}