export const NetworkSimulation = {
    NODE_RADIUS: 0.01,
    NODES_DISTANCE_MULTIPLIER: 0.8,
    CHARGE_STRENGTH: -100,
    LINK_WIDTH: 2,
    NODE_LABEL_FONT_SIZE_MULTIPLIER: 0.03,
    LINK_LABEL_FONT_SIZE_MULTIPLIER: 0.02,
    NODE_TEXT_WIDTH: 150,
    NODE_TEXT_HEIGHT: 20,
}

export const Colors = {
    PRIMARY: '#2C3C5B',
    SECONDARY: '#0AC5A8',
    TERTIARY: '#D3D3D3'
}