export enum ActionEnum {
    NONE,
    CREATE_POINT,
    CREATE_SEGMENT,
    CREATE_LINE,
    CREATE_RAY,
    CREATE_CIRCLE,
    SET_PERPENDICULARITY,
    SET_PARALLELISM,
    CREATE_MID_PERPENDICULAR,
    CREATE_BISECTOR,
    SET_SEGMENT_LENGHT,
    SET_ANGLE_MEASURE,
    ENTER_EQUATION
};