export const Colors = {
    PRIMARY: '#2C3C5B',
    SECONDARY: '#0AC5A8',
    TERTIARY: '#808080'
}

export const Sizes = {
    STROKE_WIDTH: 3,
    TICK_WIDTH: 2,
    POINT_SIZE: 2,
    TICKS_DISTANCE: 1,
    FORMULAS_SECTION_MARGIN: 0.05,
    FORMULAS_LINE_HEIGHT: 0.1,
    TEXT_FONT: 14,
};

export const Naming = {
    CAPITAL_LETTERS: 'ABCDEFGHIJKLMNOPQRSTUWVXYZ',
    LOWERCASE_LETTERS: 'abcdefghijklmnopqrstuwvxyz',
};

export const Options = {
    ALLOW_CREATING_POINTS_FOR_LINES_AND_CIRCLES_CREATING: true,
    ALLOW_CREATING_POINTS_FOR_COMPLEX_CONSTRUCTIONS: true,
    ALLOW_CREATING_POINTS_FOR_POLYGONS_CREATING: true,
}